export const experienceMap: Utils.ExperienceItems[] = [
  {
    name: 'HTML',
    year: 2019,
    type: 'frontend',
    icon: 'html',
  },
  {
    name: 'CSS',
    year: 2019,
    type: 'frontend',
    icon: 'css',
  },
  {
    name: 'Javascript',
    year: 2019,
    type: 'language',
    icon: 'javascript',
  },
  {
    name: 'Bootstrap',
    year: 2019,
    type: 'frontend',
    icon: 'bootstrap',
  },
  {
    name: 'SASS',
    year: 2019,
    type: 'frontend',
    icon: 'sass',
  },
  {
    name: 'Figma',
    year: 2020,
    type: 'frontend',
    icon: 'figma',
  },
  {
    name: 'ReactJS',
    year: 2020,
    type: 'frontend',
    icon: 'react',
  },
  {
    name: 'Styled Components',
    year: 2020,
    type: 'frontend',
    icon: 'styledComponents',
  },
  {
    name: 'Material UI',
    year: 2020,
    type: 'frontend',
    icon: 'materialui',
  },
  {
    name: 'NodeJS',
    year: 2020,
    type: 'backend',
    icon: 'nodejs',
  },
  {
    name: 'ExpressJS',
    year: 2020,
    type: 'backend',
    icon: 'expressJS',
  },
  {
    name: 'Typescript',
    year: 2020,
    type: 'language',
    icon: 'typescript',
  },
  {
    name: 'Git',
    year: 2020,
    type: 'infra',
    icon: 'git',
  },
  {
    name: 'NextJS',
    year: 2021,
    type: 'frontend',
    icon: 'nextJS',
  },
  {
    name: 'MantineUI',
    year: 2021,
    type: 'frontend',
    icon: 'mantineui',
  },
  {
    name: 'Docker',
    year: 2021,
    type: 'infra',
    icon: 'docker',
  },
  {
    name: 'MongoDB',
    year: 2021,
    type: 'backend',
    icon: 'mongoDb',
  },
  {
    name: 'PostgresDB',
    year: 2021,
    type: 'backend',
    icon: 'postgres',
  },
  {
    name: 'Insomnia',
    year: 2021,
    type: 'infra',
    icon: 'insomnia',
  },
  {
    name: 'Postman',
    year: 2021,
    type: 'infra',
    icon: 'postman',
  },
  {
    name: 'Heroku',
    year: 2021,
    type: 'infra',
    icon: 'heroku',
  },
  {
    name: 'AWS',
    year: 2022,
    type: 'infra',
    icon: 'aws',
  },
  {
    name: 'ElectronJS',
    year: 2022,
    type: 'frontend',
    icon: 'electron',
  },
  {
    name: 'Jest',
    year: 2022,
    type: 'tests',
    icon: 'jest',
  },
  {
    name: 'Playwright',
    year: 2022,
    type: 'tests',
    icon: 'playwright',
  },
  {
    name: 'PuppeterJS',
    year: 2022,
    type: 'tests',
    icon: 'puppeter',
  },
  {
    name: 'React Native',
    year: 2022,
    type: 'frontend',
    icon: 'react',
  },
  {
    name: 'Expo',
    year: 2022,
    type: 'infra',
    icon: 'expo',
  },
  {
    name: 'SvelteJS',
    year: 2023,
    type: 'frontend',
    icon: 'svelte',
  },
  {
    name: 'TailwindJS',
    year: 2023,
    type: 'frontend',
    icon: 'tailwind',
  },
  {
    name: 'NestJS',
    year: 2023,
    type: 'backend',
    icon: 'nestJS',
  },
  {
    name: 'Clojure',
    year: 2023,
    type: 'language',
    icon: 'clojure',
  },
  {
    name: 'Java',
    year: 2023,
    type: 'language',
    icon: 'java',
  },
  {
    name: 'Android Studio',
    year: 2023,
    type: 'frontend',
    icon: 'androidStudio',
  },
  {
    name: 'Spring Boot',
    year: 2023,
    type: 'backend',
    icon: 'springBoot',
  },
  {
    name: 'SeleniumJS',
    year: 2023,
    type: 'tests',
    icon: 'selenium',
  },
];
