export const urls = {
  krdsEmail: 'mailto:klessitonrds@gmail.com',
  linkedin: 'http://linkedin.com/in/klessitonrds',
  facebook: 'https://www.facebook.com/klessitom.rodrigues/',
  github: 'http://github.com/KlessitonRodrigues',
  githubProfile: 'http://github.com/KlessitonRodrigues',
  personalPage: 'https://djc7924qzcvck.cloudfront.net',
  personalPageRep: 'https://github.com/KlessitonRodrigues/personal-cv',
  jsBackupRep: 'https://github.com/KlessitonRodrigues/javascript-krds/',
  gameFinderRepo: 'https://github.com/KlessitonRodrigues/game-finder',
  consoleUIRepo: 'https://github.com/KlessitonRodrigues/game-station',
  encryptEasyRepo: 'https://github.com/KlessitonRodrigues/easy-encrypt',
  quizRepo: 'https://github.com/KlessitonRodrigues/quiz-app',
  translatePwa: 'https://github.com/KlessitonRodrigues/translation-pwa',
  whatsapp: 'https://wa.me/5589994009646',
  whatsappWeb: 'https://web.whatsapp.com/send/?phone=5589994009646',
};
